name: CI Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install MinGW-w64 cross-compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
        
    - name: Verify cross-compiler installation
      run: |
        x86_64-w64-mingw32-g++ --version
        x86_64-w64-mingw32-windres --version
        
    - name: Build application
      run: |
        make clean
        make all
        
    - name: Verify build output
      run: |
        ls -la bin/
        file bin/mm.exe
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: mm-exe-${{ github.sha }}
        path: bin/mm.exe
        retention-days: 30
        
    - name: Upload build info
      uses: actions/upload-artifact@v4
      with:
        name: build-info-${{ github.sha }}
        path: |
          bin/mm.exe
          README.md
          CHANGELOG.md
        retention-days: 30
        if-no-files-found: ignore